# Generated by Django 5.0 on 2024-02-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_create',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_last_change',
        ),
    ]
